# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170630_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='language',
        ),
        migrations.RemoveField(
            model_name='account',
            name='timezone',
        ),
    ]
