# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170630_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='language',
        ),
        migrations.RemoveField(
            model_name='account',
            name='timezone',
        ),
    ]
