# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('category', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('origin', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('item', models.CharField(max_length=30, unique=True)),
                ('admin_time', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('prep_time', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('field_time', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('admin_material', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('prep_material', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('field_material', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantity_assesement', models.CharField(choices=[('units', 'Per unit'), ('square feet', 'Square foot'), ('linear feet', 'Linear foot'), ('square meters', 'Square meter'), ('linear meters', 'Linear meter')], max_length=12, verbose_name='Quantity assesement method')),
                ('order_if_below', models.SmallIntegerField()),
                ('discontinued', models.DateField(blank=True, null=True)),
                ('order_now', models.BooleanField(default=False)),
                ('units_damaged_or_lost', models.SmallIntegerField(default=0)),
                ('quantity', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Usable quantity')),
                ('quantity_called_for', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='images/product/', verbose_name='Image', width_field='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
                ('no_longer_available', models.BooleanField(default=False)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Base')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'ordering': ['item'],
            },
        ),
    ]
