# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('category', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'equipment Category',
                'verbose_name_plural': 'equipment Categories',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='JobTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('origin', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('tool', models.CharField(max_length=30, unique=True)),
                ('tool_type', models.CharField(choices=[('personal', 'Personal'), ('company', 'Company'), ('rental', 'Rental')], default='Damaged', max_length=10)),
                ('initial_usage', models.DateField(auto_now_add=True)),
                ('condition', models.CharField(choices=[('good', 'Usable'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('sent out for repair', 'Out for repair')], default='good', max_length=20)),
                ('incident', models.DateField(blank=True, null=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Base')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'ordering': ['tool'],
            },
        ),
    ]
