# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 19:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_auto_20170628_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_warehouse', models.BooleanField(default=False, help_text='Designates whether this staff member has warehouse permissions.', verbose_name='warehouse')),
                ('is_financial', models.BooleanField(default=False, help_text='Designates this staff member has financial permissions.', verbose_name='finance')),
                ('is_service', models.BooleanField(default=False, help_text='Designates this staff member has services permissions.', verbose_name='service')),
                ('is_manager', models.BooleanField(default=False, help_text='Designates this staff member has schedule and client permissions.', verbose_name='manager')),
                ('is_maintenance', models.BooleanField(default=False, help_text='Designates this staff member has maintenance permissions.', verbose_name='maintenance')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
