# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('day', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayStaffLogDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('origin', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('start', models.TimeField(verbose_name='start')),
                ('end', models.TimeField(verbose_name='end')),
                ('actual_start', models.TimeField(verbose_name='actual start')),
                ('actual_end', models.TimeField(verbose_name='actual end')),
                ('hole', models.BooleanField(default=False, verbose_name='schedule hole')),
                ('full', models.BooleanField(default=False, verbose_name='full')),
                ('over_time', models.BooleanField(default=False, verbose_name='over time')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_log.DayLog', verbose_name='day for log')),
            ],
            options={
                'verbose_name': "Staff's Overall Time For Day",
                'verbose_name_plural': "Staff's Overall Times For Day",
            },
        ),
        migrations.CreateModel(
            name='DayStaffLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('origin', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('start', models.TimeField(verbose_name='start')),
                ('end', models.TimeField(verbose_name='end')),
                ('actual_start', models.TimeField(verbose_name='actual start')),
                ('actual_end', models.TimeField(verbose_name='actual end')),
                ('slug_for_item', models.SlugField(blank=True)),
                ('reference', models.CharField(max_length=30, verbose_name='reference')),
                ('note', models.CharField(max_length=300, verbose_name='note')),
                ('complete', models.BooleanField(default=False, verbose_name='complete')),
                ('cancelled', models.BooleanField(default=False, verbose_name='cancelled')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_log.DayStaffLogDetails', verbose_name='day log for entry')),
            ],
            options={
                'verbose_name': "Staff's Item Entry For Day Log",
                'verbose_name_plural': "Staff's Item Entries For Day Log",
                'ordering': ['day', 'start'],
            },
        ),
        migrations.CreateModel(
            name='StaffLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('origin', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=12, verbose_name='Day of the week')),
                ('scheduled_start', models.TimeField(default='07:00', verbose_name='start time of day')),
                ('scheduled_end', models.TimeField(default='17:00', verbose_name='end time of day')),
            ],
            options={
                'verbose_name': "Staff's Scheduled Hours For Day Of The Week",
                'verbose_name_plural': "Staff's Scheduled Hours For Days Of The Week",
            },
        ),
    ]
