# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_log', '0003_daystafflogdetails_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daystafflogdetails',
            options={'ordering': ['staff', 'day'], 'verbose_name': "Staff's Overall Time For Day", 'verbose_name_plural': "Staff's Overall Times For Day"},
        ),
        migrations.AlterModelOptions(
            name='stafflog',
            options={'ordering': ['staff'], 'verbose_name': "Staff's Scheduled Hours For Day Of The Week", 'verbose_name_plural': "Staff's Scheduled Hours For Days Of The Week"},
        ),
        migrations.AddField(
            model_name='stafflog',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Staff Member'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='daystafflogdetails',
            unique_together=set([('day', 'staff')]),
        ),
        migrations.AlterUniqueTogether(
            name='stafflog',
            unique_together=set([('staff', 'day')]),
        ),
    ]
