# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0007_order_time_requirements_filled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_log', '0005_auto_20170728_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('activity', models.CharField(max_length=50, verbose_name='activity')),
            ],
            options={
                'verbose_name': 'Activity Type',
                'verbose_name_plural': 'Activity Types',
                'ordering': ['activity'],
            },
        ),
        migrations.CreateModel(
            name='LoggedDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('day', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTimeSlotEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slotactivity', to='time_log.GenericActivity', verbose_name='activity')),
            ],
            options={
                'verbose_name': 'Scheduled Time Slot',
                'verbose_name_plural': 'Sscheduled Time Slots',
                'ordering': ['work_order'],
            },
        ),
        migrations.CreateModel(
            name='StaffLogDetailsForDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('origin', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('actual_start', models.TimeField(verbose_name='actual start')),
                ('actual_end', models.TimeField(verbose_name='actual end')),
                ('forecasted_hours_for_day', models.DecimalField(decimal_places=3, max_digits=5)),
                ('actual_hours_for_day', models.DecimalField(decimal_places=3, max_digits=5)),
                ('full', models.BooleanField(default=False, verbose_name='full')),
                ('over_time', models.BooleanField(default=False, verbose_name='over time')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daylogdetail', to='time_log.LoggedDay', verbose_name='Day for log')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffday', to=settings.AUTH_USER_MODEL, verbose_name='Staff Member')),
            ],
            options={
                'verbose_name': "Staff's Overall Time For Day",
                'verbose_name_plural': "Staff's Overall Times For Day",
                'ordering': ['staff', 'day'],
            },
        ),
        migrations.AlterModelOptions(
            name='availabilityforday',
            options={'ordering': ['staff', 'day'], 'verbose_name': "Staff's Scheduled Hours For Day Of The Week", 'verbose_name_plural': "Staff's Scheduled Hours For Days Of The Week"},
        ),
        migrations.AlterField(
            model_name='availabilityforday',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeavail', to=settings.AUTH_USER_MODEL, verbose_name='Staff Member'),
        ),
        migrations.AddField(
            model_name='scheduledtimeslotentry',
            name='staff_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffslot', to='time_log.StaffLogDetailsForDay', verbose_name='Staff Day'),
        ),
        migrations.AddField(
            model_name='scheduledtimeslotentry',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorder', to='work_order.Order', verbose_name='work order'),
        ),
        migrations.AlterUniqueTogether(
            name='stafflogdetailsforday',
            unique_together=set([('day', 'staff')]),
        ),
    ]
