# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_log', '0006_auto_20170731_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledtimeslotentry',
            options={'ordering': ['work_order'], 'verbose_name': 'Scheduled Time Slot', 'verbose_name_plural': 'Scheduled Time Slots'},
        ),
        migrations.AlterField(
            model_name='scheduledtimeslotentry',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workorder', to='work_order.Order', verbose_name='work order'),
        ),
        migrations.AlterField(
            model_name='stafflogdetailsforday',
            name='actual_end',
            field=models.TimeField(blank=True, null=True, verbose_name='actual end'),
        ),
        migrations.AlterField(
            model_name='stafflogdetailsforday',
            name='actual_hours_for_day',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stafflogdetailsforday',
            name='actual_start',
            field=models.TimeField(blank=True, null=True, verbose_name='actual start'),
        ),
        migrations.AlterField(
            model_name='stafflogdetailsforday',
            name='forecasted_hours_for_day',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
