# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_log', '0009_auto_20170801_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtimeslotentry',
            name='end',
            field=models.TimeField(default='7:00', verbose_name='scheduled end'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledtimeslotentry',
            name='start',
            field=models.TimeField(default='7:00', verbose_name='scheduled start'),
            preserve_default=False,
        ),
    ]
