# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_log', '0011_auto_20170801_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafflogdetailsforday',
            name='actual_end',
        ),
        migrations.RemoveField(
            model_name='stafflogdetailsforday',
            name='actual_hours_for_day',
        ),
        migrations.RemoveField(
            model_name='stafflogdetailsforday',
            name='actual_start',
        ),
        migrations.RemoveField(
            model_name='stafflogdetailsforday',
            name='forecasted_hours_for_day',
        ),
        migrations.RemoveField(
            model_name='stafflogdetailsforday',
            name='full',
        ),
        migrations.RemoveField(
            model_name='stafflogdetailsforday',
            name='over_time',
        ),
        migrations.RemoveField(
            model_name='stafflogdetailsforday',
            name='scheduled_end',
        ),
        migrations.RemoveField(
            model_name='stafflogdetailsforday',
            name='scheduled_start',
        ),
    ]
