# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_log', '0012_auto_20170801_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtimeslotentry',
            name='firm',
            field=models.BooleanField(default=False, verbose_name='firm schedule'),
        ),
    ]
