# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('category', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Base',
                'verbose_name_plural': 'Base',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='PartsForService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=7)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Product')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('origin', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('service_description', models.CharField(max_length=30, unique=True)),
                ('additional_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('hourly_additional', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('service_no_longer_available', models.BooleanField(default=False)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Base')),
                ('job_tools', models.ManyToManyField(blank=True, to='equipment.JobTool')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['base', 'service_description'],
            },
        ),
        migrations.AddField(
            model_name='partsforservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='service.Service'),
        ),
    ]
