# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 12:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('origin', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('invoice', models.CharField(max_length=200, verbose_name='Invoice description')),
                ('plu', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Invoice ID')),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_by', models.DateField(default=datetime.datetime(2017, 7, 23, 12, 54, 49, 118475))),
                ('conflict', models.BooleanField(default=False)),
                ('conflict_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Conflict description/resolution')),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('paid_in_full', models.BooleanField(default=False)),
                ('over_paid', models.BooleanField(default=False)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='images/operations_invoice/', verbose_name='Image', width_field='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
                ('log', models.TextField(blank=True, default='', max_length=30000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceAlteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('origin', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('plu', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Payment ID')),
                ('transaction_update', models.CharField(choices=[('Paid', 'Payment'), ('Cost', 'Additional Cost'), ('Credit', 'Company Reimbursement')], max_length=30)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_note', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='operation_finance.Invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set([('invoice', 'plu')]),
        ),
    ]
