# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 18:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_by',
            field=models.DateField(default=datetime.datetime(2017, 7, 23, 18, 46, 31, 739544)),
        ),
    ]
