# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 19:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_finance', '0003_auto_20170628_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_by',
            field=models.DateField(default=datetime.datetime(2017, 7, 23, 19, 25, 31, 347896)),
        ),
    ]
