# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_finance', '0004_auto_20170628_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_by',
            field=models.DateField(default=datetime.datetime(2017, 7, 23, 21, 14, 55, 448942)),
        ),
    ]
