# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 12:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_finance', '0010_auto_20170630_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_by',
            field=models.DateField(default=datetime.datetime(2017, 7, 25, 12, 29, 51, 983107)),
        ),
    ]
