# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 03:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_finance', '0014_auto_20170630_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_by',
            field=models.DateField(default=datetime.datetime(2017, 7, 26, 3, 33, 23, 90781)),
        ),
    ]
