# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_finance', '0015_auto_20170701_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_by',
            field=models.DateField(default=datetime.datetime(2017, 7, 26, 14, 25, 52, 548452)),
        ),
    ]
