# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 17:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_finance', '0016_auto_20170701_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_by',
            field=models.DateField(default=datetime.datetime(2017, 7, 28, 17, 15, 24, 270704)),
        ),
    ]
