# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_finance', '0017_auto_20170703_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_by',
            field=models.DateField(default=datetime.datetime(2017, 7, 29, 16, 7, 12, 549098)),
        ),
    ]
