# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 02:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_finance', '0021_auto_20170712_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_by',
            field=models.DateField(default=datetime.datetime(2017, 8, 6, 2, 25, 6, 711742)),
        ),
    ]
