# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 14:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_finance', '0023_auto_20170712_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_by',
            field=models.DateField(default=datetime.datetime(2017, 8, 6, 14, 54, 13, 649130)),
        ),
    ]
