# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20170718_1600'),
        ('operation_finance', '0033_auto_20170720_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='plu',
            field=models.CharField(default=2, max_length=30, verbose_name='Invoice ID'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice',
        ),
    ]
