# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20170718_1600'),
        ('operation_finance', '0034_auto_20170721_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='plu',
            field=models.CharField(max_length=60, unique=True, verbose_name='Invoice ID'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set([('vendor', 'plu')]),
        ),
    ]
