# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation_finance', '0035_auto_20170721_0052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicealteration',
            options={'verbose_name': 'Alteration', 'verbose_name_plural': 'Alterations'},
        ),
        migrations.RemoveField(
            model_name='invoicealteration',
            name='plu',
        ),
    ]
