# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_finance', '0036_auto_20170721_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicealteration',
            name='transaction_update',
            field=models.CharField(choices=[('Payment', 'Payment(-)'), ('Discount', 'Discount(-)'), ('Fee', 'Fee/Additional Cost(+)'), ('Error-Add', 'Add to previous entry amount due to             under error entry(-)'), ('Error-Off', 'Take from previous entry amount due             to over error entry(+)')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='vendorconflict',
            unique_together=set([('invoice', 'conflict_description')]),
        ),
    ]
