# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('description', models.CharField(max_length=30, verbose_name='Job description')),
                ('note', models.TextField(blank=True, max_length=300, null=True)),
                ('scheduled', models.BooleanField(default=False)),
                ('sent_to_finance', models.BooleanField(default=False)),
                ('postponed', models.BooleanField(default=False, verbose_name='Order postponed')),
                ('pulled', models.DateTimeField(blank=True, null=True, verbose_name='Product pulled')),
                ('work_initiated', models.DateTimeField(blank=True, null=True)),
                ('work_completed', models.DateTimeField(blank=True, null=True)),
                ('order_created', models.DateField(auto_now_add=True)),
                ('closed_out', models.DateTimeField(blank=True, null=True)),
                ('job_history', models.TextField(blank=True, default='', max_length=30000, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(blank=True, to='service.Service')),
            ],
            options={
                'ordering': ['order_created', 'client'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('client', 'description')]),
        ),
    ]
