# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0003_remove_order_scheduled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postponed',
        ),
    ]
