# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0004_remove_order_postponed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postponed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Service postponed'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Product scheduled'),
        ),
    ]
