# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 15:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0005_auto_20170725_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
