# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0006_auto_20170726_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_requirements_filled',
            field=models.BooleanField(default=False),
        ),
    ]
