# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerConflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('origin', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('conflict_description', models.CharField(max_length=300, verbose_name='Conflict description')),
                ('conflict_resolution', models.CharField(blank=True, max_length=300, null=True, verbose_name='Conflict resolution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('origin', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('tax', models.DecimalField(decimal_places=2, default=6.0, max_digits=4)),
                ('give_price_quote', models.BooleanField(default=False)),
                ('paid_in_full', models.BooleanField(default=False)),
                ('over_paid', models.BooleanField(default=False)),
                ('closed_out', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('log', models.TextField(blank=True, default='', max_length=30000, null=True)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Pricing')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work_order.Order')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-origin', 'work_order'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceAlteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('origin', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('transaction_update', models.CharField(choices=[('Payment', 'Payment(-)'), ('Discount', 'Discount(-)'), ('Fee', 'Fee/Additional Cost(+)'), ('Error-Add', 'Add to previous entry amount due to             under error entry(-)'), ('Error-Off', 'Take from previous entry amount due             to over error entry(+)')], max_length=30)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_note', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='customer_finance.Invoice')),
            ],
            options={
                'verbose_name': 'Alteration',
                'verbose_name_plural': 'Alterations',
            },
        ),
        migrations.CreateModel(
            name='PriceQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('origin', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('total_price_quoted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_on_quote', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_quote', to='customer_finance.Invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customerconflict',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict', to='customer_finance.Invoice'),
        ),
    ]
