# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_finance', '0004_auto_20170721_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_invoice', to='work_order.Order'),
        ),
    ]
